### PR TITLE
fix: parse `allowed_account_types` in provider config

### LINKED ISSUE #89: `allowed_account_types` field in provider config is ignored
**Describe the bug**
1. on provider create/update, `allowed_account_types` field is ignored and not being passed to db
2. empty `allowed_account_types` failed to use default value automatically

### PR DESCRIPTION
**Pull request by rahmatrhd**
closes #89 

proto changes: https://github.com/odpf/proton/pull/74

### CODE REVIEW

File: appeal/service.go [hunk 1]
```diff
@@ -129,25 +129,27 @@ func (s *Service) Create(appeals []*domain.Appeal) error {
 			activeAppeals[a.AccountID][a.ResourceID] != nil &&
 			activeAppeals[a.AccountID][a.ResourceID][a.Role] != nil {
 
-			if p.Config.Appeal.AllowActiveAccessExtensionIn == "" {
-				return ErrAppealFoundActiveAccess
-			}
+			if p.Config.Appeal != nil {
```
Comment (snorlacs) [inline appeal/service.go:132]: @rahmatrhd what is the expected behaiour if `p.Config.Appeal` is nil

**Review by snorlacs — APPROVED** [review]

File: appeal/service.go (hunk 1 above)
Comment (rahmatrhd) [reply appeal/service.go:132]: guardian will ignore the appeal config, because rules like `AllowActiveAccessExtensionIn` and `AllowPermanentAccess ` are not present
